### ISSUE TITLE
Set marker on the map with AdvancedMarkerElement

### ISSUE THREAD

**Issue by FireOlex** [Wild-Siena/google-maps-bundle#1]
**Description**
We want to implement AdvancedMarkerElement from GoogleMaps. It should be possible to add one or more markers to the map.

**Describe the solution you'd like**
Extend the MapOptions Model it needs a new property ```string $mapId```
Extend the GoogleMap Model it needs a new property ```array $markers``` to pass a list of lat and lng to the map.

Extend the stimulus controller to process the new values.
As mentioned above we will use the ```AdvancedMarkerElement``` from the GoogleMaps js api.

**Tasks**

- [ ] Extend MapOptions Model.
- [ ] Extend GoogleMap Model.
- [ ] Extend stimulus controller.
- [ ] Adjust tests.
- [ ] Write changelog.
- [ ] Adjust docs

**Additional context**
![Bildschirmfoto 2024-07-04 um 14 49 51](https://github.com/Wild-Siena/google-maps-bundle/assets/6445602/bbfbc582-5257-4c6b-ae3c-5c2794d79446)
